### ISSUE TITLE
How to use. 

### ISSUE THREAD

**Issue by oriolism** [edalquist/pwrcell_sunspec#1]
Hi, can you give me some guide on how to use this project? Im using the sunspect integration in HA but doesn't have all the data from the inverter. 

Regards

**Comment by edalquist** [comment]
Sure I'll get instructions written up. I'm curious how you're accessing modbus data on your system right now? I have a process but I've been wary about documenting it on the off chance Generac decides to block it.

**Comment by oriolism** [comment]
> Sure I'll get instructions written up. I'm curious how you're accessing modbus data on your system right now? I have a process but I've been wary about documenting it on the off chance Generac decides to block it.

Based on the first link that you have on the notes, it’s the same method.

**Comment by edalquist** [comment]
Just added some configuration docs on how to automate the SSH tunnel and set this up as a service. Please give those a try and report back on what other information you need.

**Comment by edalquist** [comment]
I realized I have the device_ids hard coded still here: https://github.com/edalquist/pwrcell_sunspec/blob/main/main.py#L56

I'll work on moving these to the config yaml and updating the scan.py utility to make them easier to find.

**Comment by oriolism** [comment]
Thanks for the update! Im having problems running the pwrcell-ha service. To test I replaced your harcoded device_ids with my devices but after manually run main.py im getting this error:

Traceback (most recent call last):
  File "/opt/pwrcell_sunspec/main.py", line 5, in <module>
    import pwrcell
  File "/opt/pwrcell_sunspec/pwrcell.py", line 58, in <module>
    class GeneracPwrCell():
  File "/opt/pwrcell_sunspec/pwrcell.py", line 175, in GeneracPwrCell
    def __read_points(self, device: ss2_client.SunSpecModbusClientDeviceTCP, points: dict[ss2_client.SunSpecModbusClientPoint, Callable[[ss2_client.SunSpecModbusClientPoint]]], tries=3):
  File "/usr/lib/python3.10/_collections_abc.py", line 430, in __new__
    raise TypeError(
TypeError: Callable must be used as Callable[[arg, ...], result].

Any recommendations?

**Comment by edalquist** [comment]
The only thing I can think of is I'm running it under Python 3.9

I am by no means a python expert so maybe there are things I'm doing that don't play nice with python 3.10?

**Comment by oriolism** [comment]
Running fine on Python 3.9 but had to change the installation directory to Home due to permission issues. OP Mode and Battery min/max configuration also working fine. I was trying to add the inverter OP State(Grid Connected, Islanding, Standby, Disabled)  to the sensor without success. 

On homeassistant.py I added this :

    self.__define_sensor(
        self.__pwrcell.inverter.inverter[0].St,
        device_id='pwrcell_inverter',
        sensor_id='inverter_state')

What else its needed to add that sensor?

Regards

**Comment by oriolism** [comment]
It looks like that's the problem, there's no state sensor on homeasssistant.py.

**Comment by edalquist** [comment]
Can you share the JSON config for the inverter_state from MQTT?

**Comment by oriolism** [comment]
I don't have that JSON config but I had that sensor as a rest sensor on HA. 
On homeassistant.py  it should be:

    self.__define_sensor(
        self.__pwrcell.inverter.inverter[0].StVnd,
        device_id='pwrcell_inverter',
        sensor_id='inverter_state')

   SENSOR
   
    - platform: rest
      resource: http://192.168.0.20:8085/device/3/model/inverter
      name: PWRcell Inverter
      scan_interval: 10
      json_attributes_path: "$.fixed"
      value_template: "OK"
      json_attributes:
        - W
        - PhVphA
        - PhVphB
        - St
        - StVnd
        - Evt1  
   
   
   TEMPLATE 
   
         
    - name: "Inverter Vendor OP State"
      unique_id: inverter_op_state
      state: "{{ state_attr('sensor.pwrcell_inverter', 'StVnd' ) }}"
      
   
    - name: "Inverter Operation State"   
      state: >
        {% if is_state("sensor.inverter_vendor_op_state", "2080") -%}
          Grid Connected
        {% elif is_state("sensor.inverter_vendor_op_state", "2096") -%}
          Islanding
        {% elif is_state("sensor.inverter_vendor_op_state", "773") -%}
          Standby
        {% elif is_state("sensor.inverter_vendor_op_state", "16") -%}
          Disabled
        {%- else -%}
          Unknow
        {%- endif %}

**Comment by oriolism** [comment]
I will close this issue an open a request for the state sensor since its not related to the original issue.
