### ISSUE TITLE
PV Links Incorrect decimal Value. 

### ISSUE THREAD

**Issue by oriolism** [edalquist/pwrcell_sunspec#3]
All the PV Links are reporting wrong decimal values for example 78.0 W instead of 780 W.

**Comment by oriolism** [comment]
This is not a mayor issue, I can use a template sensor on HA to fix this.

**Comment by oriolism** [comment]
> I remember seeing this when testing, I'm wondering if the sunspec data being returned from your rebus doesn't have the scale factor set correctly. At one point I thought I had an option to override the scale-factor when configuring sensors but I can't find that code now.

The scale factor looks ok on the scan. 

string_combiner:
  ID:  404
  L:  25
  DCA_SF:  -2
  DCAhr_SF:  0
  DCV_SF:  -1
  **DCW_SF:  0
  DCWh_SF:  0**
  DCAMax:  1300
  N:  0
  Evt:  0
  EvtVnd:  None
  DCA:  293
  DCAhr:  None
  DCV:  2761
  Tmp:  47
  DCW:  790
  DCPR:  None
  DCWh:  1499645
  InDCA_SF:  0
  InDCAhr_SF:  0
  InDCV_SF:  0
  InDCW_SF:  0
  InDCWh_SF:  0

**Comment by oriolism** [comment]
Changing this on parcel.py  fixed the problem:

      def __fix_device(self, device: ss2_client.SunSpecModbusClientDeviceTCP):
    """
    Apply various overrides/fixes to devices after they have been loaded
    """
    for string_combiner in device.models.get(404, []):
      # DCW has a scale factor point of DCW_SF but that is set to zero in the system. Clear the sf point
      # reference and manually set the sf_value to -1
      string_combiner.DCW.sf = None
      string_combiner.DCW.sf_value = None

**Comment by edalquist** [comment]
Ah, so it must be my PvLinks that report the wrong scale value :D

I'm going to re-open this and see about moving the scale-factor override into the config file

**Comment by PeterGrace** [comment]
It appears that some of my PVLinks match eric's situation, and others don't -- I do think this needs to be configurable per pv-link in the yaml or have some other way to detect scaling may be awry (for instance, I have 2x6 solaria 360w panels on a pvlink and I'm getting 9000W output from one pvlink and 900W from the other PVLink.  900W would be reasonable for sun position at the moment.

I bet the scale factor is related to firmware version:


![image](https://user-images.githubusercontent.com/967365/198841742-8cb27418-451a-4e8a-9bd8-dcc7536e960a.png)

**Comment by edalquist** [comment]
+1 to adding a scale-factor override in the config. Honestly I'm not really happy with the current config and hard-coding of all the attributes you care about. I'd like to restructure things so the config both lists the devices and paths to attributes you want exposed. If things were structured like that it would be easy to add per-attribute overrides to things like scale factor.

Also you both might be interested in https://github.com/edalquist/sunspec_explorer it is in-progress but with a little more work it will allow MUCH better visualization of all the possible data.

**Comment by PeterGrace** [comment]
Not the most elegant way to solve this, but:
```
  def __fix_device(self, device: ss2_client.SunSpecModbusClientDeviceTCP):
    """
    Apply various overrides/fixes to devices after they have been loaded
    """
    for string_combiner in device.models.get(404, []):
      # DCW has a scale factor point of DCW_SF but that is set to zero in the system. Clear the sf point
      # reference and manually set the sf_value to -1
      if device.common[0].Vr.value == "634_13700":
        string_combiner.DCW.sf = None
        string_combiner.DCW.sf_value = None
      else:
        logging.info("Found older pvlink firmware, adjusting scale factor.")
        string_combiner.DCW.sf = None
        string_combiner.DCW.sf_value = -1
```

Now at least my production layout seems sane: 
![image](https://user-images.githubusercontent.com/967365/198843113-b7137cda-cca3-4dfb-aef1-b50b8f04d557.png)

**Comment by PeterGrace** [comment]
As an update -- after two days of watching, it appears that pvlinks with the older firmware will "wake up" after a night and have a different scale factor, but, if you stop and restart pwrcell_sunspec it seems to resolve itself?  Not sure what conditions contribute to this behavior but it definitely seems to only be happening on older firmware pvlinks thus far.  
![image](https://user-images.githubusercontent.com/967365/199009549-260cb0d7-6a6a-4c23-86ea-2ccc63d315f2.png)

**Comment by edalquist** [comment]
Not perfect but better than before!
