### ISSUE TITLE
Support for state/alarms sensors. 

### ISSUE THREAD

**Issue by oriolism** [edalquist/pwrcell_sunspec#4]
I would be great  to know the actual state of the inverter, pv links and battery and in case of any error on the system receive a notification with a HA automation. Model model_64259.json has good sensors that can be useful in this case.

**Comment by edalquist** [comment]
Fixed in Commit [12962dc](https://github.com/edalquist/pwrcell_sunspec/commit/12962dc926e6fdd9aca26316b54ea1281533ec93)
